# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHpogXSfQYQDojvOGf0CBCYQrOfeqwzX
"""

import requests

CITY = "Austin"
LAT = 30.2672
LON = -97.7431

BOT_TOKEN = "8346674370:AAGKmhpbz7KrelZM9io6ADPqmmbj9a7qq5o"
CHAT_ID = "8138932005"

def fetch_temperature(lat, lon):
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": lat,
        "longitude": lon,
        "current_weather": True
    }
    r = requests.get(url, params=params, timeout=20)
    r.raise_for_status()
    return r.json()["current_weather"]["temperature"]

def send_to_telegram(text):
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    requests.post(url, data={"chat_id": CHAT_ID, "text": text}, timeout=20)

temp = fetch_temperature(LAT, LON)

message = f"""🌤 Weather Report
City: {CITY}
Current Temperature: {temp} °C
"""

send_to_telegram(message)

print("✅ Weather report sent to Telegram")

